apiVersion: v1
kind: Service
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  type: NodePort
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    protocol: TCP
  selector:
    app: fastapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - image: ghcr.io/rnacentral/rnacentral-export:{{ .Values.branch }}
          name: fastapi
          imagePullPolicy: Always
          command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
          - containerPort: {{ .Values.port }}
          resources:
            requests:
              memory: {{ .Values.requestsMemory }}
              cpu: {{ .Values.requestsCPU }}
            limits:
              memory: {{ .Values.limitsMemory }}
          volumeMounts:
            - name: rnacentral-species-specific-ids
              mountPath: /srv/fasta
            - name: export-results
              mountPath: /srv/results
            - name: logs
              mountPath: /srv/logs
          envFrom:
          - secretRef:
              name: variables
          - configMapRef:
              name: {{ .Values.proxy }}
      volumes:
        - name: rnacentral-species-specific-ids
          persistentVolumeClaim:
            claimName: rnacentral-species-specific-ids
        - name: export-results
          persistentVolumeClaim:
            claimName: export-results
        - name: logs
          persistentVolumeClaim:
            claimName: logs
