apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: export-results
  name: export-results
spec:
  storageClassName: standard-nfs-production
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
