apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: logs
  name: logs
spec:
  storageClassName: standard-nfs-production
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
