apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: rnacentral-species-specific-ids
  name: rnacentral-species-specific-ids
spec:
  storageClassName: standard-nfs-production
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
